question_data = [
        {
            "category": "Science & Nature",
            "type": "boolean",
            "difficulty": "medium",
            "question": "The Neanderthals were a direct ancestor of modern humans.",
            "correct_answer": "False",
            "incorrect_answers": ["True"]
        },
        {"category": "Science & Nature", "type": "boolean", "difficulty": "easy",
         "question": "Igneous rocks are formed by excessive heat and pressure.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "hard",
         "question": "The retail disc of Tony Hawk&#039;s Pro Skater 5 only comes with the tutorial.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
         "question": "The HTML5 standard was published in 2014.", "correct_answer": "True",
         "incorrect_answers": ["False"]},
        {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
         "question": "The name of the main character of the video game &quot;The Legend of Zelda&quot;, is Zelda.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
         "question": "The main character in the &quot;Half-Life&quot; franchise is named Morgan Freeman.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
         "question": "The first computer bug was formed by faulty wires.", "correct_answer": "False",
         "incorrect_answers": ["True"]}, {"category": "Animals", "type": "boolean", "difficulty": "medium",
                                          "question": "An octopus can fit through any hole larger than its beak.",
                                          "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Geography", "type": "boolean", "difficulty": "easy",
         "question": "Greenland is almost as big as Africa.", "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
         "question": "English new wave musician Gary Numan founded the video game development company Facepunch Studios in March 2009.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
         "question": "&quot;Typewriter&quot; is the longest word that can be typed using only the first row on a QWERTY keyboard.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Geography", "type": "boolean", "difficulty": "medium",
         "question": "The surface area of Russia is slightly larger than that of the dwarf planet Pluto.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Art", "type": "boolean", "difficulty": "medium",
         "question": "Vincent van Gogh cut off one of his ears.", "correct_answer": "True",
         "incorrect_answers": ["False"]},
        {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
         "question": "There are 6 legendary cards in &quot;Clash Royale&quot;.", "correct_answer": "False",
         "incorrect_answers": ["True"]},
        {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
         "question": "The game &quot;Battlefield 1&quot; takes place during World War I.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
         "question": "&quot;Windows NT&quot; is a monolithic kernel.", "correct_answer": "False",
         "incorrect_answers": ["True"]}, {"category": "Science: Gadgets", "type": "boolean", "difficulty": "easy",
                                          "question": "The communication protocol NFC stands for Near-Field Control.",
                                          "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
         "question": "MacOS is based on Linux.", "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "History", "type": "boolean", "difficulty": "easy",
         "question": "United States President John F. Kennedy was assassinated during his presidential motorcade in Atlanta, Georgia on November 22nd, 1963.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Politics", "type": "boolean", "difficulty": "easy",
         "question": "Russia passed a law in 2013 which outlaws telling children that homosexuals exist.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "History", "type": "boolean", "difficulty": "easy",
         "question": "Adolf Hitler was a german soldier in World War I.", "correct_answer": "True",
         "incorrect_answers": ["False"]}, {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
                                           "question": "The open source program Redis is a relational database server.",
                                           "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
         "question": "AMD created the first consumer 64-bit processor.", "correct_answer": "True",
         "incorrect_answers": ["False"]}, {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
                                           "question": "In Alfred Hitchcock&#039;s film &#039;Psycho&#039; it is said he used chocolate syrup to simulate the blood in the famous shower scene from ",
                                           "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Geography", "type": "boolean", "difficulty": "easy",
         "question": "There are no deserts in Europe.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean", "difficulty": "easy",
         "question": "Gosho Aoyama Made This Series: (Detective Conan \/ Case Closed!)", "correct_answer": "True",
         "incorrect_answers": ["False"]}, {"category": "Entertainment: Books", "type": "boolean", "difficulty": "easy",
                                           "question": "&quot;Elementary, my dear Watson&quot; is a phrase that is never truly said within the Conan Doyle books of Sherlock Holmes.",
                                           "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
         "question": "The Windows 7 operating system has six main editions.", "correct_answer": "True",
         "incorrect_answers": ["False"]},
        {"category": "Geography", "type": "boolean", "difficulty": "easy",
         "question": "California is larger than Japan.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
         "question": "The Konami Code is known as Up, Up, Down, Down, Left, Right, Right, Left, B, A, Start.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Sports", "type": "boolean", "difficulty": "easy",
         "question": "In association football, or soccer, a corner kick is when the game restarts after someone scores a goal.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Entertainment: Television", "type": "boolean", "difficulty": "easy",
         "question": "In Battlestar Galactica (2004), Cylons were created by man as cybernetic workers and soldiers.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
         "question": "In RuneScape, one must complete the &quot;Dragon Slayer&quot; quest before equipping Rune Platelegs.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean", "difficulty": "hard",
         "question": "Druid is a mage class in &quot;Log Horizon&quot;.", "correct_answer": "False",
         "incorrect_answers": ["True"]},
        {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
         "question": "In &quot;Super Mario World&quot;, the rhino mini-boss, Reznor, is named after the lead singer of the band &quot;Nine Inch Nails&quot;.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean", "difficulty": "medium",
         "question": "In &quot;JoJo&#039;s Bizarre Adventure&quot;, Father Enrico Pucchi uses a total of 3 stands in Part 6: Stone Ocean.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
         "question": "Linus Sebastian is the creator of the Linux kernel, which went on to be used in Linux, Android, and Chrome OS.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Entertainment: Music", "type": "boolean", "difficulty": "hard",
         "question": "Pete Townshend&#039;s solo album, &quot;White City: A Novel&quot;, is set in the metropolitan area of Chicago.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
         "question": "Haggis is traditionally ate on Burns Night.", "correct_answer": "True",
         "incorrect_answers": ["False"]}, {"category": "Politics", "type": "boolean", "difficulty": "easy",
                                           "question": "Former president Theodore Roosevelt (1900-1908)  ran for another term under the Progressive Party in 1912.",
                                           "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
         "question": "In career mode of &quot;Need for Speed: Underground 2&quot;, the first car the player can drive is the BMW M3 GTR.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Vehicles", "type": "boolean", "difficulty": "easy",
         "question": "BMW M GmbH is a subsidiary of BMW AG that focuses on car performance.", "correct_answer": "True",
         "incorrect_answers": ["False"]}, {"category": "Science: Mathematics", "type": "boolean", "difficulty": "easy",
                                           "question": "An isosceles triangle has two sides of equal length as opposed to three.",
                                           "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Entertainment: Television", "type": "boolean", "difficulty": "easy",
         "question": "&quot;The Simpsons&quot; family is named after creator Matt Groening&#039;s real family.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
         "question": "In the game &quot;Until Dawn&quot; Emily is the only playable character who can be killed by another playable character directly.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Entertainment: Music", "type": "boolean", "difficulty": "medium",
         "question": "&quot;Neutral Milk Hotel&quot; is a real band.", "correct_answer": "True",
         "incorrect_answers": ["False"]}, {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
                                           "question": "The Python programming language gets its name from the British comedy group &quot;Monty Python.&quot;",
                                           "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Science: Computers", "type": "boolean", "difficulty": "hard",
         "question": "The T-Mobile Sidekick smartphone is a re-branded version of the Danger Hiptop.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Entertainment: Music", "type": "boolean", "difficulty": "easy",
         "question": "Lead Singer Rivers Cuomo of American rock band Weezer attended Harvard.",
         "correct_answer": "True",
         "incorrect_answers": ["False"]}, {"category": "Entertainment: Books", "type": "boolean", "difficulty": "easy",
                                           "question": "Shub-Niggurath is a creature that was created by \tJ. R. R. Tolkien in his novel &quot;The Lord of The Rings&quot;.",
                                           "correct_answer": "False", "incorrect_answers": ["True"]}]
